import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { AppSidebar } from "~/components/shared/AppSidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { Separator } from "~/components/ui/separator";
import DropdownChangeTheme from "~/components/shared/DropdownChangeTheme";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <section>
            <SidebarProvider>
                <AppSidebar />
                <SidebarInset>
                    <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
                        <SidebarTrigger className="-ml-1" />
                        <Separator orientation="vertical" className="mr-2 h-4" />
                        <div className="flex flex-1 items-center justify-end">
                            <DropdownChangeTheme />
                        </div>
                    </header>
                    <main className="flex flex-1 flex-col gap-4 p-4">
                        {children}
                        <div className="min-h-[100vh] flex-1 rounded-xl bg-muted/50 md:min-h-min" />
                    </main>
                </SidebarInset>
            </SidebarProvider>
        </section>
    );
}
